# Generated by Django 2.2.24 on 2021-10-07 08:12

import appBackend.forms
import appBackend.models
from django.conf import settings
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ルーム名')),
                ('talk', djongo.models.fields.EmbeddedField(model_container=appBackend.models.Talk, model_form_class=appBackend.forms.TalkForm, null=True)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
